fmt:
   pnpm exec prettier --write .
build:
    pnpm react-router build

dev: 
   pnpm react-router dev

start:
   pnpm react-router-serve ./build/server/index.js

typecheck:
   pnpm react-router typegen && tsc

lint:
   pnpm dlx eslint .
