services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8088:8080
    networks:
      - backend
  ollama:
    image: ollama/ollama
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - ${OLLAMA_MOUNT_PATH}:/root/.ollama
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
